"""
Alembic migration script for RTC enhancements

Run with:
  cd backend
  alembic revision --autogenerate -m "Add RTC live tracking and participants"
  alembic upgrade head

This adds:
- RTCSession: is_live, started_at, ended_at, participant_count, viewer_count, invite_code
- RTCParticipant: New table for tracking session participants
- User: storage_used_mb for storage quota tracking
"""

# Note: This is a documentation file
# Actual migration will be auto-generated by Alembic

print("""
To create the migration:

cd /home/fatih/proPod/backend
source venv/bin/activate
alembic revision --autogenerate -m "Add RTC live tracking and participants"
alembic upgrade head

This will:
1. Add new columns to rtc_sessions table
2. Create rtc_participants table
3. Add storage_used_mb to users table
4. Create necessary indexes
""")
