"""Add updated_at fields to PodcastLike and PodcastBookmark models

Revision ID: 3dd09391d55b
Revises: 8437146af7b0
Create Date: 2025-09-20 23:28:45.757073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dd09391d55b'
down_revision: Union[str, Sequence[str], None] = '8437146af7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_bookmarks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('podcast_likes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast_likes', 'updated_at')
    op.drop_column('podcast_bookmarks', 'updated_at')
    # ### end Alembic commands ###
