"""Add RTC participants and live status

Revision ID: 788d6da0a208
Revises: 707783153751
Create Date: 2026-02-21 15:46:51.823640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '788d6da0a208'
down_revision: Union[str, Sequence[str], None] = '707783153751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rtc_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('peer_id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connection_quality', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['rtc_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rtc_participants_session_active', 'rtc_participants', ['session_id', 'is_active'], unique=False)
    op.create_index('idx_rtc_participants_user', 'rtc_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_rtc_participants_id'), 'rtc_participants', ['id'], unique=False)
    op.create_index(op.f('ix_rtc_participants_peer_id'), 'rtc_participants', ['peer_id'], unique=False)
    op.create_index(op.f('ix_rtc_participants_session_id'), 'rtc_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_rtc_participants_user_id'), 'rtc_participants', ['user_id'], unique=False)
    op.add_column('rtc_sessions', sa.Column('is_live', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('rtc_sessions', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('rtc_sessions', sa.Column('ended_at', sa.DateTime(), nullable=True))
    op.add_column('rtc_sessions', sa.Column('participant_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('rtc_sessions', sa.Column('viewer_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('rtc_sessions', sa.Column('invite_code', sa.String(length=12), nullable=True))
    op.alter_column('rtc_sessions', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('rtc_sessions', 'media_mode',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'video'::character varying"))
    op.alter_column('rtc_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('rtc_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rtc_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rtc_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index('idx_rtc_sessions_live', 'rtc_sessions', ['is_live', 'is_public', 'created_at'], unique=False)
    op.create_index(op.f('ix_rtc_sessions_id'), 'rtc_sessions', ['id'], unique=False)
    # Populate invite_code for any existing rows before applying unique constraint
    op.execute("""
        UPDATE rtc_sessions
        SET invite_code = UPPER(SUBSTRING(MD5(id::TEXT || RANDOM()::TEXT), 1, 12))
        WHERE invite_code IS NULL
    """)
    op.create_index(op.f('ix_rtc_sessions_invite_code'), 'rtc_sessions', ['invite_code'], unique=True)
    op.add_column('users', sa.Column('storage_used_mb', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'storage_used_mb')
    op.drop_index(op.f('ix_rtc_sessions_invite_code'), table_name='rtc_sessions')
    op.drop_index(op.f('ix_rtc_sessions_id'), table_name='rtc_sessions')
    op.drop_index('idx_rtc_sessions_live', table_name='rtc_sessions')
    op.alter_column('rtc_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rtc_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('rtc_sessions', 'duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rtc_sessions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'created'::character varying"))
    op.alter_column('rtc_sessions', 'media_mode',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'video'::character varying"))
    op.alter_column('rtc_sessions', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('rtc_sessions', 'invite_code')
    op.drop_column('rtc_sessions', 'viewer_count')
    op.drop_column('rtc_sessions', 'participant_count')
    op.drop_column('rtc_sessions', 'ended_at')
    op.drop_column('rtc_sessions', 'started_at')
    op.drop_column('rtc_sessions', 'is_live')
    op.drop_index(op.f('ix_rtc_participants_user_id'), table_name='rtc_participants')
    op.drop_index(op.f('ix_rtc_participants_session_id'), table_name='rtc_participants')
    op.drop_index(op.f('ix_rtc_participants_peer_id'), table_name='rtc_participants')
    op.drop_index(op.f('ix_rtc_participants_id'), table_name='rtc_participants')
    op.drop_index('idx_rtc_participants_user', table_name='rtc_participants')
    op.drop_index('idx_rtc_participants_session_active', table_name='rtc_participants')
    op.drop_table('rtc_participants')
    # ### end Alembic commands ###
