"""add_processing_time_seconds_to_ai_data

Revision ID: 8be1dbe47bbb
Revises: c545a6726641
Create Date: 2026-01-31 14:40:50.113829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be1dbe47bbb'
down_revision: Union[str, Sequence[str], None] = 'c545a6726641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_ai_data', sa.Column('processing_time_seconds', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast_ai_data', 'processing_time_seconds')
    # ### end Alembic commands ###
